vich_uploader:
    db_driver: orm

    mappings:
        decorations:
            uri_prefix: /uploads/image
            upload_destination: '%kernel.project_dir%/public/uploads/image'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        tableaux:
            uri_prefix: /uploads/image
            upload_destination: '%kernel.project_dir%/public/uploads/image'
            namer: Vich\UploaderBundle\Naming\UniqidNamer